### ISSUE TITLE
Compatibility with Material Components

### ISSUE THREAD

**Issue by brookmg** [nambicompany/expandable-fab#1]
Is this project compatible with the material components from google? Specifically with the [BottomAppBar](https://material.io/develop/android/components/app-bars-bottom).

**Comment by kabumere** [comment]
Yes! It was compatible with Snackbar already, but your question led me to make a change so that now it's also compatible with BottomAppBar (and any other current and future material components). 

These changes are available starting from v0.9.2 which is currently in the repo and Maven Central, so you can include it with just `implementation 'com.nambimobile.widgets:expandable-fab:0.9.2'`.

I also put an example using BottomAppBar in the example app that is in the repo. The fragment in question is called `BottomAppBar Compatibility`. Give it a run and customize it to see if it fits your needs. Let me know if you have any questions.

An example where the Overlay does not cover the BottomAppBar:
![](https://raw.githubusercontent.com/nambicompany/expandable-fab/master/docs/gallery/bottom_app_bar_center.gif)

An example where the Overlay DOES cover the BottomAppBar:
![](https://raw.githubusercontent.com/nambicompany/expandable-fab/master/docs/gallery/bottom_app_bar_covered_right.gif)

**Comment by brookmg** [comment]
Amazing work! Will definitely check it out for my projects. Thanks for the quick reply as well.
