### ISSUE TITLE
How to remove the fab option circle

### ISSUE THREAD

**Issue by aneebali** [nambicompany/expandable-fab#27]
I want to remove the fab option circle i want only label is there any possibility ?

**Comment by kabumere** [comment]
@aneebali: yes it's possible. By default, the FabOption does not show any icon at all. Don't set an icon if you don't want one.

If you actually meant the ExpandableFab (which shows a white plus sign by default), then set [efabIcon](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFab.kt#L73) to null.

**Comment by aneebali** [comment]
i am talking about the circle i dont want the circle

**Comment by kabumere** [comment]
@aneebali what circle? Are you talking about the button itself?

If so, you can set the color of your FabOption to be transparent (`app:fab_color="#00FFFFFF"` in XML or `fabOption.fabOptionColor = Color.parseColor("#00FFFFFF")` in code) so it's no longer visible.

However, the FabOption will still take space on the screen (even though you won't be able to see it due to its color). If you want to reduce its size as well, please look at the [CustomSizesFragment](https://github.com/nambicompany/expandable-fab/blob/master/examples/src/main/kotlin/com/nambimobile/examples/efab/CustomSizesFragment.kt) and its [layout file](https://github.com/nambicompany/expandable-fab/blob/master/examples/src/main/res/layout/custom_sizes_fragment.xml).

Please take time to read the documentation and look through the [examples](https://github.com/nambicompany/expandable-fab/tree/master/examples) app as well, as they both detail how to customize your ExpandableFab widget,

**Comment by aneebali** [comment]
@kabumere  thankyou i got it and one more thing how i can reduce spaces from fabOptions

**Comment by kabumere** [comment]
@aneebali it depends on what space you're referring to.

- expandableFab.[firstFabOptionMarginPx](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-expandable-fab/first-fab-option-margin-px.html) controls the vertical margin between the first FabOption and the ExpandableFab itself.
- expandableFab.[successiveFabOptionMarginPx](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-expandable-fab/successive-fab-option-margin-px.html) controls the vertical margin between successive FabOptions (1st to 2nd, 2nd to 3rd, 3rd to 4th, etc).
- label.[marginPx](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-label/margin-px.html) controls the horizontal margin between the Label and the view it is attached to (either an ExpandableFab or a FabOption).

**Comment by aneebali** [comment]
Thankyou ♥️
