### ISSUE TITLE
Rotation animation bug when size is not 24.

### ISSUE THREAD

**Issue by GraxCode** [nambicompany/expandable-fab#30]
When size is not 24, as soon as the rotation animation on the ExpandableFab is started, the icon seems to stick into the upper left corner (does also not return after the animation finished). I am setting the icon dynamically using setEfabIcon, and my Fab menu is placed on the bottom left.

**Comment by kabumere** [comment]
Hey @GraxCode,

The examples app covers the use case of using custom sizes. There are a couple of attributes that Android requires you to set, or else you get wonky behavior when the icon is animating. 

When you run the examples app, look at the 'Custom Sizes' screen to see if that's the functionality you're looking for. If it is, you'll be interested in the [CustomSizesFragment's layout file](https://github.com/nambicompany/expandable-fab/blob/master/examples/src/main/res/layout/custom_sizes_fragment.xml).

Also, please see the documentation on the [FabSize enum](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/FabSize.kt), as it shows an example of the attributes you need to set in order to get custom sizes icons to animate properly. This documentation is also captured in both the JavaDoc and KDoc.

**Comment by GraxCode** [comment]
Didn't know that. Pretty hidden in the documentation to find that out. You should try making it more obvious and not let it look like a bug.

**Comment by kabumere** [comment]
Hey @GraxCode,

To be fair, the directions for using custom sizes are listed in:

1) the examples app (as shown in my first message)
2) the documentation for FabSize enum (as shown in my first message)
3) the documentation for [efabSize](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFab.kt#L90) when working programmatically
4) the documentation for [fabOptionSize](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFab.kt#L144) when working programmatically
5) the documentation for [efabSize](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/res/values/attrs.xml#L164) when working through XML layouts
6) the documentation for [fabOptionSize](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/res/values/attrs.xml#L196) when working through XML layouts

So whether you're working programmatically or through XML layouts, or even if you're just running the example app without typing a line of code, I figured the steps were pretty clearly stated.

If you have any suggestions on where else it should be stated so it doesn't seem hidden though, let me know!

**Comment by GraxCode** [comment]
Wasn't really obvious to me as the fab size is not the same as the icon size and i expected the icon to be scaled according to the fab size, and as a normal lazy developer I am generally too lazy to read the docs for an unknown library to then find out it's unusable anyway in some cases. :)

**Comment by kabumere** [comment]
@GraxCode lol, angry and passive aggressive because you didn't RTFM. It's okay boss. Enjoy your day.
