### ISSUE TITLE
FR: Extended FAB

### ISSUE THREAD

**Issue by dkrivoruchko** [nambicompany/expandable-fab#9]
Please add option for [Extended FAB](https://material.io/components/buttons-floating-action-button#extended-fab) instead of current label. With different text on closed and opened states.

**Comment by kabumere** [comment]
Hey @dkrivoruchko,

I played around with Extended FABs for a bit awhile back, and decided not to include it in the library. Animations got kind of wonky when the Extended FAB was hiding and showing its label (since it was dynamically shrinking and growing in size). This means the current way the library handles anchoring and margins between views would need to change specifically for Extended FABs. It's doable I'm sure, but I decided the effort was unjustified since ExpandableFab already has regular label support.

Feel free to submit a pull request if you decide to contribute an Extended FAB implementation to the library, however.
